- name: "Setting up a firewall"

      action: lineinfile dest=/etc/default/ufw regexp="^IPV6" line="IPV6=yes" state=present

    - ufw: rule=allow port={% raw %}{{ item }}{% endraw %} proto=tcp

      with_items:

        - 22

    - ufw: state=enabled policy=deny